# Generated by Django 3.1 on 2021-06-26 19:24

import code_service.core.abstract_models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scheme",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=code_service.core.abstract_models._uuid_generator,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                (
                    "scheme_type",
                    models.CharField(
                        choices=[
                            ("HIGH_RISK", "HIGH_RISK"),
                            ("RETIREMENT", "RETIREMENT"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=code_service.core.abstract_models._uuid_generator,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stashaway.scheme",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.userprofile",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="MonthlyRecurringDepositSchedule",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=code_service.core.abstract_models._uuid_generator,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("day_of_month", models.IntegerField()),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stashaway.portfolio",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Deposit",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=code_service.core.abstract_models._uuid_generator,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stashaway.portfolio",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
