# Generated by Django 3.1 on 2021-06-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stashaway", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="amount",
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
