# Generated by Django 3.1 on 2021-06-26 19:24

import code_service.core.abstract_models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=code_service.core.abstract_models._uuid_generator,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(db_index=True, max_length=30)),
            ],
            options={"abstract": False,},
        ),
    ]
